apiVersion: apps/v1
kind: Deployment
metadata:
  name: league-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: league-app
  template:
    metadata:
      labels:
        run: league-app
    spec:
      containers:
      - name: league-app
        image: gcr.io/leagueai/league-app:v1
        imagePullPolicy: Always
        env:
          - name: DB_URI
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_URI
        resources:
          requests:
            memory: "900Mi"
            cpu: "600m"
          limits:
            memory: "1000Mi"
            cpu: "700"
      nodeSelector:
        component: ml