apiVersion: apps/v1
kind: Deployment
metadata:
  name: league-app
spec:
  replicas: 4
  selector:
    matchLabels:
      run: league-app
  template:
    metadata:
      labels:
        run: league-app
    spec:
      containers:
      - name: league-app
        image: gcr.io/leagueai/league-app:v1
        imagePullPolicy: Always
        env:
          - name: DB_URI
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_URI
      nodeSelector:
        component: ml