apiVersion: "v1"
kind: "Service"
metadata:
  name: "league-app-service"
  namespace: "default"
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    run: "league-app"
  type: "LoadBalancer"
  loadBalancerIP: "104.197.59.31"